services:
- type: web
  name: next-js
  runtime: node
  rootDir: ./web
  buildCommand: npm install; npm run build:self-host
  startCommand: npm start
  autoDeploy: false
  envVars:
  - key: NODE_ENV
    value: production
  - key: OPENAI_API_KEY
    sync: false
  - key: SOLO_API_KEY
    sync: false
