name: Manual Plugin Release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Version increment type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: "patch"

jobs:
  check_release:
    runs-on: ubuntu-latest
    outputs:
      is_releasing: ${{ steps.check.outputs.is_releasing }}
    steps:
      - id: check
        name: Check for running release workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          running=$(gh api /repos/${{ github.repository }}/actions/runs \
            --jq '.workflow_runs[] | select(.status=="in_progress" and (.name=="Release Obsidian Plugin" or .name=="Manual Plugin Release")) | .id' \
            | wc -l)
          if [ "$running" -gt "1" ]; then
            echo "is_releasing=true" >> $GITHUB_OUTPUT
            echo "::error::A release is already in progress. Please wait for it to complete."
            exit 1
          else
            echo "is_releasing=false" >> $GITHUB_OUTPUT
          fi

  release:
    needs: check_release
    if: needs.check_release.outputs.is_releasing != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update versions and generate artifacts
        id: release_prep
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Build all packages including release-notes
          pnpm build --filter "@file-organizer/release-notes"
          
          # Use the optimized release process
          RELEASE_DATA=$(node -e "
            const { updateVersions, generateReleaseArtifacts, prepareReleaseArtifacts, generateReleaseNotes } = require('./packages/release-notes/dist');
            
            async function run() {
              const versionInfo = await updateVersions('${{ github.event.inputs.increment }}');
              console.log('Version info:', JSON.stringify(versionInfo));
              
              await generateReleaseArtifacts(versionInfo.previous, {
                repoRoot: process.cwd(),
                openAIApiKey: process.env.OPENAI_API_KEY
              });
              
              const artifacts = await prepareReleaseArtifacts(versionInfo.new);
              console.log('Generated artifacts:', artifacts);
              
              const notes = await generateReleaseNotes(versionInfo.previous, {
                repoRoot: process.cwd(),
                openAIApiKey: process.env.OPENAI_API_KEY
              });
              
              return { versionInfo, notes };
            }
            
            run().catch(console.error);
          ")
          
          echo "RELEASE_DATA<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_DATA" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Parse release data
          VERSION=$(echo "$RELEASE_DATA" | jq -r '.versionInfo.new')
          RELEASE_NAME=$(echo "$RELEASE_DATA" | jq -r '.notes.name')
          RELEASE_DESC=$(echo "$RELEASE_DATA" | jq -r '.notes.description')
          TECHNICAL_CHANGES=$(echo "$RELEASE_DATA" | jq -r '.notes.technicalChanges | join("\n- ")')
          
          # Create release notes markdown
          {
            echo "# $RELEASE_NAME"
            echo ""
            echo "$RELEASE_DESC"
            echo ""
            echo "## Technical Changes"
            echo "- $TECHNICAL_CHANGES"
            echo ""
            echo "## SHA-256 Checksums"
            cat release-artifacts/checksums.txt
          } > release-notes.md
          
          # Create the GitHub release
          gh release create "$VERSION" \
            --title="$RELEASE_NAME" \
            --notes-file=release-notes.md \
            --draft=false \
            release-artifacts/main.js \
            release-artifacts/styles.css \
            release-artifacts/manifest.json \
            release-artifacts/checksums.txt
